CREATE TABLE exchange_rates (
                      id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      base_currency_id int,
                      target_currency_id int,
                      rate float(6) NOT NULL
);